<<<<<<< HEAD
<<<<<<< HEAD
app = "discord-custom-bot"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[experimental]
  auto_rollback = true
=======
# fly.toml app configuration file generated for discord-custom-bot on 2025-09-06T01:59:30+02:00
=======
# fly.toml app configuration file generated for szkieletor on 2025-09-06T20:20:47+02:00
>>>>>>> f6b1b7c (Update GitHub Actions workflow for Fly deploy)
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'szkieletor'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
>>>>>>> 5fa6ce1 (Add fly.io config)
