name: Deploy to Wispbyte

on:
  push:
    branches:
      - main   # or whatever branch you want

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright requests
          python -m playwright install

      - name: Run deploy script
        env:
          WISPBYTE_EMAIL: ${{ secrets.WISPBYTE_EMAIL }}
          WISPBYTE_PASSWORD: ${{ secrets.WISPBYTE_PASSWORD }}
          WISPBYTE_SERVER_URL: ${{ secrets.WISPBYTE_SERVER_URL }}
        run: |
          python deploy_wispbyte.py
