name: Upload to Wispbyte

on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          pip install playwright requests
          python -m playwright install

      - name: Create ZIP of repo
        run: |
          zip -r bot.zip .

      - name: Upload to Wispbyte
        env:
          WISPBYTE_EMAIL: ${{ secrets.WISPBYTE_EMAIL }}
          WISPBYTE_PASSWORD: ${{ secrets.WISPBYTE_PASSWORD }}
          WISPBYTE_SERVER_URL: ${{ secrets.WISPBYTE_SERVER_URL }}
        run: |
          python .github/scripts/upload_wispbyte.py
