name: Upload to Wispbyte

on:
  push:
    branches:
      - main  # or your branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install Python packages
        run: |
          pip install playwright requests
          python -m playwright install

      # Step 4: Run Playwright script to upload
      - name: Upload to Wispbyte
        env:
          WISPBYTE_EMAIL: ${{ secrets.WISPBYTE_EMAIL }}
          WISPBYTE_PASSWORD: ${{ secrets.WISPBYTE_PASSWORD }}
          WISPBYTE_SERVER_URL: ${{ secrets.WISPBYTE_SERVER_URL }}
        run: |
          python .github/scripts/upload_wispbyte.py
