name: Upload to Wispbyte

on:
  push:
    branches:
      - main  

jobs:
  upload:
    runs-on: self-hosted  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright requests
          python -m playwright install

      - name: Run Wispbyte upload
        env:
          WISPBYTE_EMAIL: ${{ secrets.WISPBYTE_EMAIL }}
          WISPBYTE_PASSWORD: ${{ secrets.WISPBYTE_PASSWORD }}
          WISPBYTE_SERVER_URL: ${{ secrets.WISPBYTE_SERVER_URL }}
        run: |
          python upload_wispbyte.py
