name: Upload to Wispbyte

on:
  push:
    branches:
      - main  

jobs:
  upload:
    runs-on: self-hosted  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set Execution Policy
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          python -m playwright install

      - name: Zip repository
        shell: pwsh
        run: |
          $zipPath = "$env:GITHUB_WORKSPACE\repo.zip"
          if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::CreateFromDirectory($env:GITHUB_WORKSPACE, $zipPath)
          Write-Output "Repo zipped to $zipPath"

      - name: Upload to Wispbyte
        shell: pwsh
        run: |
          $wispUrl = $env:WISBYTE_SERVER_URL   # set this as a secret in your repo
          $zipPath = "$env:GITHUB_WORKSPACE\repo.zip"
          $wc = New-Object System.Net.WebClient
          $wc.Headers.Add("Authorization", "Bearer $env:WISBYTE_API_KEY")  # add your API key as a secret
          $wc.UploadFile($wispUrl, "POST", $zipPath)
          Write-Output "Upload complete!"
